name: StampRallyPlugin
version: '${project.version}'
main: dev.shiro8613.stamprallyplugin.StampRallyPlugin
api-version: '1.20'
commands:
  srp:
    aliases: [ srp ]
    description: srp
    usage: srp get